services:
  # 1️⃣ Base de datos SQL Server
  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TuPasswordFuerte123!"
    ports:
      - "1434:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - /Users/bernardocornejo/Documents/inversiones/init:/init
    networks:
      - demo-net-inversiones
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'TuPasswordFuerte123!' -C -Q 'SELECT 1'" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # 2️⃣ Script de inicialización
  sqlserver-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlserver-init
    depends_on:
      sqlserver-db:
        condition: service_healthy
    entrypoint: /bin/bash
    command: >
      -c "echo 'Esperando 10s extra para asegurar SQL listo...' &&
           sleep 10 &&
           /opt/mssql-tools/bin/sqlcmd -S sqlserver-db -U sa -P 'TuPasswordFuerte123!' -i /init/init-db.sql"
    networks:
      - demo-net-inversiones
    volumes:
      - /Users/bernardocornejo/Documents/inversiones/init:/init

  # 3️⃣ Aplicación Spring Boot
  demo-app-inversiones:
    build: .
    container_name: demo-app-inversiones
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      sqlserver-init:
        condition: service_completed_successfully
    networks:
      - demo-net-inversiones
    restart: unless-stopped

networks:
  demo-net-inversiones:

volumes:
  mssql_data:
