# ===========================
# PERFIL LOCAL
# ===========================
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=inversiones_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: TuPasswordFuerte123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8081

---
# ===========================
# PERFIL DOCKER
# ===========================
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:sqlserver://sqlserver-db:1433;databaseName=inversiones_db;encrypt=false
    username: sa
    password: TuPasswordFuerte123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8080
